language: ruby
cache:
  - bundler
  - yarn
rvm:
  - 2.7.x
services:
  - postgresql
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - "psql -c 'create database travis_ci_test;' -U postgres"
  - "bundle exec rake db:migrate"