language: ruby
cache: bundler
dist: xenial
rvm: 2.7.3
env:
 - DB=pgsql
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
 — bundle install — jobs=3 — retry=3
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec