language: ruby
rvm:
  - 2.7.3
before_script:
  - bundle install --jobs=3 --retry=3
  - psql -c 'create database travis_ci_test;' -U postgres
  - bundle exec rake db:schema:load
script:
  - bundle exec rake spec
cache:
  - bundler
services:
  - postgresql
notifications:
  email: false