language: ruby
rvm:
  - 3.0
services:
  - postgresql
before_script:
  - gem pristine rake
  - bundle install --jobs=3 --retry=3
  # - yarn
  - "psql -c 'create database classnotes_build3_test;' -U postgres"
  - "bundle exec rake db:migrate"
