language: ruby
rvm:
  - 2.7.3
cache:
  - bundler
services:
  - postgresql
before_script:
  - bundle install --jobs=3 --retry=3
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
script:
  - bundle exec rake test
  - bundle exec rake test:system
notifications:
  email: false