# frozen_string_literal: true
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Note.create!([
  {title: "BJJ Advanced", date: "2020-09-06", instructor: "Juniao ", technique: "Triangle. Entry, controlling one sleeve, pop legs over. Alternatively, control both sleeves and weave knee over opp's head. The inside of my knee must be on his neck. Then, hold shin, adjust and finish. If opp postures up, go for the arm bar.", user_id: 1, tag_list: nil},
  {title: "BJJ Advanced", date: "2020-09-14", instructor: "Kywan", technique: "Sweep from closed guard. Go for cross choke, deep grip. If opp blocks the second arm, control one of his, pulling it with my elbow back. Step on this side, tilt my hips, and bring my knee across his chest and sweep.", user_id: 1, tag_list: nil},
  {title: "No Gi", date: "2021-08-11", instructor: "Marcelo", technique: "Amazing seminar today with Marcelo Garcia", user_id: 1, tag_list: nil},
  {title: "No Gi", date: "2020-09-05", instructor: "Bruno", technique: "Self defence from the ground. Keep legs inbetween me and opp. If opp is going for a kick, adjust so that my technical stand up blocks his kicking leg. Push with free leg, swing it back and stand up. Second drill; closed guard cross choke. Strong hand in deep is the MOST IMPORTANT THING. Once this hand is in, options open. If I am struggling to get a grip with the second hand, I can shift hips to a side and reach over to grab the gi and finish. ", user_id: 1, tag_list: nil},
  {title: "BJJ Intermediate", date: "2021-09-01", instructor: "Nima", technique: "Began with some specific from half guard, then Nima taught us a sweep he likes to use. You load up your partner on the knee shield before rolling over your shoulder and popping your legs through - partner should end up under my side control.", user_id: 1, tag_list: nil},
  {title: "BJJ All Levels", date: "2020-09-08", instructor: "Bruno", technique: "Cross choke from closed guard. If opp is framing well and keeping my chest on the ground, I want to lift my hips up and shoot them to one side. Lifting is very important. This was I can get a deeper grip inside his collar with my dominant hand and tighten up the choke. Details, snap opp's collar into my grip if possible to make the grip tighter. ", user_id: 1, tag_list: nil},
  {title: "BJJ Intermediate", date: "2020-09-11", instructor: "Charles", technique: "1. Wrist lock. Opp pushes me, I grab his tricep/behind elbow, pull towards me and bow my head down on his inside. 2. Americana from mount. Get into high mount, get his top arm and with both my arms straight, lead my weight down to isolate it. Then while pinning his wrist, weave my forearm through. Accelerate motorbike handle, bring elbow towards his side and lift the elbow. 3. Alternatively, if his striaghtens his arm and bridges away, go for the armbar.", user_id: 1, tag_list: nil},
  {title: "BJJ Fundamentals", date: "2020-09-17", instructor: "Juniao ", technique: "Knee on belly. From side control, tuck thumb into opps collar and grip his outside hip, pushing down jump up, knee across solar plexus. Leg closer to his hips goes across, other leg posts out. If he rolls, take his arm and arm bar. Then to get into mount, slip foot across when he bridges. ", user_id: 1, tag_list: nil},
  {title: "BJJ Intermediate", date: "2020-09-21", instructor: "Charles", technique: "Pulling guard. Make grip on opps sleeve with outside arm and collar with the inside (BOTH ON SAME SIDE OF GI). Fake a trip so he steps back, then step on his hip (same side as grips) and pull into open guard. Either close the guard or sweep from here. ", user_id: 1, tag_list: nil},
  {title: "BJJ Advanced", date: "2021-08-20", instructor: "Juniao ", technique: "Guard passing. Push down with one arm, lock elbow. Grip opps arm and swing across. Step up with foot on the side where he is armless, put weight on his chest, and stand on the other leg. Holding onto the arm posture up, tuck elbow inside his knee, step back and pass. ", user_id: 1, tag_list: nil},
  {title: "BJJ Advanced", date: "2020-09-04", instructor: "Juniao ", technique: "Closed guard. Move to triangle. Opp is throwing punches - bring knees to chest and trap one of his arms, then block the other arm with forearm and control wrist. Bring knee and foot through, adjust and finish triangle. TURTLE. Lying down, opp is across my back. Get head through his legs, look up and posture up, then lift one leg and drop the other one, finishing in closed guard or mount if poss. ", user_id: 1, tag_list: nil},
  {title: "BJJ Intermediate", date: "2020-09-12", instructor: "Bruno", technique: "Half guard to mount. In opp's half guard. Pry his legs open by driving my hips forward, then pass over his high knee. Underhook his head and pry his arm up towards his head, opening up a side of the torso so I can bring leg through and pass, finishing in mount.", user_id: 1, tag_list: nil},
  {title: "No Gi", date: "2020-09-13", instructor: "Charles", technique: "Guard pass. Get underhook under a leg while maintaining posture, then drive forward and grip across opp's neck, holding the collar. Then shift hips to the side and slide past his legs. ", user_id: 1, tag_list: nil},
  {title: "BJJ All Levels", date: "2020-09-15", instructor: "Juniao ", technique: "Arm bar from closed guard. Grip opp's wrist to my chest, weave my arm under the other one and trap his elbow down, then make cross collar grip with hand that was holding the wrist. Push away on his hip (same side as trapped elbow), shift perpendicular to him and lock his back with my legs. Get my leg over his neck, squeeze knees together and arm bar. ", user_id: 1, tag_list: nil},
  {title: "No Gi", date: "2020-09-19", instructor: "Junior", technique: "Opp in my closed guard. He tries to strangle, bring legs over his shoulders and squeeze knees while pushing hips up and cranking wrists away from each other. ", user_id: 1, tag_list: nil},
  {title: "BJJ All Levels", date: "2020-09-22", instructor: "Bruno", technique: "Half guard. Sitting on opps leg that is inbetween mine, weave arm through his thighs and grip the lower leg. Make grip with other hand on his collar, keeping arm bent to avoid Kimura, sprawl leg back, drive arm into his chin with weight on his body and get into side control.", user_id: 1, tag_list: nil},
  {title: "BJJ Fundamentals", date: "2020-10-13", instructor: "Junior", technique: "Guard passing. Grab opps leg, step towards them, place foot inbetween their legs and squat, dragging their leg over the thigh. Drive knee down and block their knee with the armpit. Then shift hips across into side control.", user_id: 1, tag_list: nil},
  {title: "BJJ Fundamentals", date: "2020-10-18", instructor: "Bruno", technique: "Takedown from behind. Arms wrapped around hips, elbow traps upper thigh and drive over. Trap shoulders with knee. Finish with Ezekiel.", user_id: 1, tag_list: nil},
  {title: "BJJ All Levels", date: "2020-10-15", instructor: "Uyi", technique: "Standing throws, pushing opp one way and sweeping leg. Also pulling guard. ", user_id: 1, tag_list: nil},
  {title: "BJJ All Levels", date: "2020-09-23", instructor: "Kywan", technique: "Breaking grip on collar. Make a grip on sleeve, tightening so the sleeve doesn't move up and down the arm, step back leaning shoulders forward, slightly over the hips, and push grip down. + Guard pass, two underhooks under legs, grab collar of opponent, put arm over his neck, drive forward and roll to the side, sliding other arm over hips.", user_id: 1, tag_list: nil},
  {title: "BJJ Fundamentals", date: "2020-09-24", instructor: "Luciano ", technique: "Throw. Grip opps arm by tricep, step in front, underhook his armpit with my elbow, drop below his hips, lift him up on my lower back and throw. (Did with Ollie, blue belt).", user_id: 1, tag_list: nil},
  {title: "BJJ Fundamentals", date: "2020-09-25", instructor: "Bruno", technique: "Straight footlock. Opps leg inbetween mine. Reach under his knee and block him from pushing his leg through by raising up my forearm (with hand stuck to my leg) and then wrap ankle with other arm. Make grip on my collar to secure and lift up. Then roll to the side (other side to gripped ankle), put knee on the floor and turn over shoulder while pushing hips forward.", user_id: 1, tag_list: nil},
  {title: "BJJ Intermediate", date: "2020-09-28", instructor: "Bruno", technique: "Spider guard (Control sleeves and control biceps with feet). Sweep - push away on one hip, and scissor with this leg and the one on bicep. Other option - pull opp into a triangle. ", user_id: 1, tag_list: nil},
  {title: "BJJ Fundamentals", date: "2020-09-29", instructor: "Junior", technique: "Side control attacks. First - switch hips so I'm leaning towards opp with back to his hips. Take his wrist, place it under my leg, lock it, and then roll on to my knees. Second - Americana. When opp bridges drive head over to other side, wrap his wrist, bring his elbow towards his body while twisting his wrist as if I am accelerating on a motobike, and bring his elbow up using my forearm. ", user_id: 1, tag_list: nil},
  {title: "BJJ All Levels", date: "2020-09-30", instructor: "Mauricio", technique: "Arm bar from standing. Opp puts hand on my head, wrap it up, secure elbow, squat while pulling wrist up. ", user_id: 1, tag_list: nil},
  {title: "No Gi", date: "2020-10-01", instructor: "Charles", technique: "Side control seminar. Aim of side control is to keep chest on chest, pry opp's arms away and above his head while maintaining pressure, to then slide knee over belly and mount. Also - switch between different side control variations depending on the situation. ", user_id: 1, tag_list: nil},
  {title: "BJJ Intermediate", date: "2020-10-03", instructor: "Bruno", technique: "Take down. Step up close to opp with weight down on grips. Sweep leg and peel his collar across to that side. Then slide knee over belly, shift hips onto his body, slide round to north south while isolating an arm, then arm bar. ", user_id: 1, tag_list: nil},
  {title: "BJJ All Levels", date: "2020-10-04", instructor: "Kywan", technique: "Ezekhiel from mount. And then Arm Bar from mount after trying the Ezekhiel. ", user_id: 1, tag_list: nil},
  {title: "No Gi", date: "2020-10-06", instructor: "Kywan", technique: "Half guard to mount. Under hook shoulder, drive head forward and bring leg through, using the other leg to assist breaking the partner's leg squeeze if necessary.", user_id: 1, tag_list: nil},
  {title: "BJJ Intermediate", date: "2020-10-08", instructor: "Junior", technique: "Opp has one of my legs. Push head away and kick leg out. Or, push opps head to outside of the body, grab his belt, push his head and back down, hook one leg and pull the other towards. ", user_id: 1, tag_list: nil},
  {title: "BJJ Fundamentals", date: "2020-10-09", instructor: "Kywan", technique: "Guillotine from North South (coming from side control).", user_id: 1, tag_list: nil},
  {title: "No Gi", date: "2020-10-10", instructor: "Kywan", technique: "Rolling escapes from side control. Create frame with arms, tuck leg in and wriggle into closed guard. Second one. Grab belt, get body at right angle to opp and roll over shoulder.", user_id: 1, tag_list: nil},
  {title: "BJJ All Levels", date: "2020-10-12", instructor: "Charles", technique: "Guard passing. Push down with one arm, lock elbow. Grip opps arm and swing across. Step up with foot on the side where he is armless, put weight on his chest, and stand on the other leg. Holding onto the arm posture up, tuck elbow inside his knee, step back and pass. ", user_id: 1, tag_list: nil},
  {title: "BJJ Intermediate", date: "2020-10-14", instructor: "Junior", technique: "Sweep from closed guard. Opp is in my closed guard, places a leg to the right to try and stand up, grip his arm on my chest, wiggle over to the planted leg, underhook it and sweep opp into mount. If opp puts his knee down I can attack the arm with an arm bar. ", user_id: 1, tag_list: nil},
  {title: "BJJ Fundamentals", date: "2020-10-16", instructor: "Bruno", technique: "Takedown from behind. Arms wrapped around hips, elbow traps upper thigh and drive over. Trap shoulders with knee. Finish with Ezekiel.", user_id: 1, tag_list: nil},
  {title: "BJJ All Levels", date: "2020-10-17", instructor: "Kywan", technique: "Open guard, control one arm. Pull across, climb up the arm and take the back. Trap leg with elbow and drive into ground.", user_id: 1, tag_list: nil}
])

User.create!([
  {email: "arthur@example.com", password: "password1", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, username: "Arthur"},
  {email: "max@example.com", password: "password1", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, username: "Max"},
  {email: "tom@example.com", password: "password1", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, username: "Tom"},
  {email: "mark@example.com", password: "password1", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, username: "Mark"},
  {email: "alan@example.com", password: "password1", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, username: "Alan"},
  {email: "bobby@example.com", password: "password1", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, username: "Bob"},
  {email: "aef@me.com", password: "password1", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, username: "asdfj"},
  {email: "guest@example.com", password: "password1", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, username: "Guest"}
])

